version: '3.8'
x-environment: &global_env
  SUPABASE_URL: https://xemeulesojjkcoajrchi.supabase.co
  SUPABASE_KEY: 
  GITHUB_TOKEN: 
services:
  api:
    environment:
      <<: *global_env
    build: 
      context: ./src/app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  airflow:
    environment:
      <<: *global_env
      AIRFLOW__EMAIL__EMAIL_BACKEND: airflow.providers.sendgrid.utils.emailer.send_email
      SENDGRID_MAIL_FROM: j.napol@tabtile.fr
      SENDGRID_API_KEY: 
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  mlflow:
    environment:
      <<: *global_env
    build:
      context: ./models/mlflow
      dockerfile: Dockerfile
    ports:
      - "5001:5000"