version: '3.8'
x-environment: &global_env
  SUPABASE_URL: https://xemeulesojjkcoajrchi.supabase.co
  SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlbWV1bGVzb2pqa2NvYWpyY2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODM3NTY4ODksImV4cCI6MTk5OTMzMjg4OX0.5dlk9erdfCZImNc-aMj8o2Fh-m-gWI9Uwro7SakgEwI
services:
  api:
    environment:
      <<: *global_env
    build: 
      context: ./src/app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  airflow:
    environment:
      <<: *global_env
      AIRFLOW__EMAIL__EMAIL_BACKEND: airflow.providers.sendgrid.utils.emailer.send_email
      GITHUB_TOKEN: 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
      SENDGRID_MAIL_FROM: j.napol@tabtile.fr
      SENDGRID_API_KEY: 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
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"