name: API Test Workflow

on:
  push:
    paths:
      - 'src/app/api/main.py'
  pull_request:
    paths:
      - 'src/app/api/main.py'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f src/app/requirements.txt ]; then pip install -r src/app/requirements.txt; fi

      - name: Run Tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          cd tests/app/api
          python -m unittest test_routes.py

