name: API Test Workflow

on:
  push:
    paths:
      - 'src/app/api/main.py'
  pull_request:
    paths:
      - 'src/app/api/main.py'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r 'src/app/requirements.txt'
          
      - name: Debug
        run: |
          pwd
          ls -l
    
      - name: Run Tests
        working-directory: tests/app/api
        run: |
          python -m unittest test_routes.py
        env: 
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
